### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DmitryFedoreev** [scottmckendry/blog#2]
Hi, I also made a website on Hugo and many people have seen such a display of the project on github as you have in the article "Moving My Blog From Ghost to Hugo". Can you tell me how to make the same display as on github or at least how to Google it

Thank you in advance
![Снимок222](https://github.com/user-attachments/assets/2c342cf7-5964-4017-b5ad-6ad0a8d8b3d1)

**Comment by scottmckendry** [comment]
Depends on your theme. I'm using the blowfish theme, so it comes with a lot of custom shortcodes out of the box, one of them being the GitHub card:

https://blowfish.page/docs/shortcodes/#github-card

If it's not included, you can make your own shortcodes. Just check Hugo's documentation.

**Comment by DmitryFedoreev** [comment]
Thank you very much. I also use this theme, but I didn't see the
documentation on the site.

сб, 2 нояб. 2024 г. в 22:35, Scott McKendry ***@***.***>:
